## 22.01.09

# 구문오류와 예외
### 구문오류
- 잘못된 명령을 입력해 발생함
- 오타나 문법적으로 필수적인 요소가 빠지진 않았는지 찾아 재코딩해야함
### 예외
- 문법적인 문제는 없는데 실행 중에 예기치 않게 발생함
- 인덱스 초과 혹은 0으로 나누기 등등
# 예외 처리 방법
- if문을 이용한 예외의 처리
  ```python
  if width.isdigit() and height.isdigit():   // if문을 통해 width, height가 숫자인지를 체크
      ~~~ 정상코드
  else:
      ~~~ 에러메시지 출력   // isdigit()의 반환값이 False일 경우
  ```
- try-except문을 이용한 예외의 처리
- try-except-else문을 이용한 예외의 처리
- try-except-else-finally문을 이용한 예외의 처리
  ```
  area = 0
  try:
      area = int(width) * int(height)
  except:
      //예외발생시 실행
  else:
      //정상코드 실행
  finally:
      //예외발생 하든 안하든 실행하는 코드 
  ```
# 예외 객체
- 코드를 실행 중 오류가 발생하면 만들어진 것으로, 오류 발생과 관련한 정보를 가지고 있음
```python
try:
    x = int(input(""))
    y = int(input(""))
    result = x / y
except ValueError as ve:     // ValueError 발생시 ve로 참조
    print("{0}: {1}".format(type(ve), ve))
except ZeroDivisionError as ze:     // ZeroDivisionError 발생시 ze로 참조
    print("{0}: {1}".format(type(ze), ze))
except Exception as ex:     // 위 두 에러를 제외한 에러 발생시
    print("{0}: {1}".format(type(ex), ex))    
```
# 강제로 예외를 발생시키는 방법
- 특정 조건에서 예외 객체를 만들어 예외를 일으킬 수 있음
```python
def calc_area(w, h):
    if w.isdigit() and h.isdigit():
        return int(w) * int(h)
    else:
        raise ValueError("숫자가 아닌 값이 입력되었습니다.") // raise 문을 이용해 강제로 ValueError 예외 상황을 일으킴
area = 0
try:
    area = calc_area(width, height)
except ValueError as ve:  // ValueError 예외발생시 예외 객체를 except문의 블록에서 ve로 참조
    ~~~
```







































